mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "BlackBear"
  expose: ["3306"]
  ports: ["13306:3306"]